version: 2
jobs:
  build-flake8:
    docker:
      - image: python:3.6.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install flake8
      - run:
          name: Lint with Flake8
          command: flake8

workflows:
  version: 2
  build:
    jobs:
      - build-flake8
