version: 2
jobs:
  flake8:
    docker:
      - image: python:3.6.2
    steps:
      - run:
          name: Install dependencies
          command: pip3 install flake8
      - run:
          name: Lint with Flake8
          command: flake8

workflows:
  version: 2
  build:
    jobs:
      - flake8
