version: 2
jobs:
  build-python-lint:
    docker:
      - image: python:3.6.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install -r requirements.test.txt
      - run:
          name: Lint with Flake8
          command: flake8
  build-python-test:
    docker:
      - image: python:3.6.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install -r requirements.test.txt
      - run:
          name: Test with pytest
          command: pytest

workflows:
  version: 2
  build:
    jobs:
      - build-python-lint
      - build-python-test
